name: Build Shadowrocket Rules

on:
  schedule:
    # 每日8时开始
    - cron:  '0 23 * * *'
  
  push:
    branches:
      - build
    paths-ignore: 
      - '**.md'
      - 'LICENSE'

  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install requirements
        run: pip3 install -r requirements.txt

      - name: Run auto-build.sh
        run: ./factory/auto_build.sh

      - name: Update lazy rules
        run: |
          rm -f lazy.conf lazy_group.conf
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy.conf
          curl -O https://raw.githubusercontent.com/LOWERTOP/Shadowrocket/main/lazy_group.conf

      - name: Generate QR codes & update README URLs
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          BRANCH: ${{ github.ref_name }}
        run: python3 factory/generate_qr.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: .
          commit-message: 'Nightly build [skip ci]'
          
